import React from 'react'
import { StyleSheet } from 'react-native';



export const styles = StyleSheet.create({
    container: {
      flex: 1,
      // backgroundColor: '#fff',
    },
    background: {
      width: '100%',
      height: '100%',
      // opacity: '20%'
    },
    backgroundImageStyle: {
      opacity: 0.5
    },
    contentContainer: {
      paddingTop: 30,
    },
    getStartedText: {
      fontSize: 17,
      color: 'rgba(96,100,109, 1)',
      lineHeight: 24,
      textAlign: 'center',
    },
    loginForm: {
      position: 'absolute',
      bottom: '20%',
      // borderStyle: 'solid',
      // borderWidth: 2,
      width: '100%'
    },
    loginInputBox: {
      // position: 'relative',
      // bottom: '0%',
      marginTop: '2%',
      marginLeft: '10%',
      marginRight: '10%',
      backgroundColor: 'white',
      opacity: 0.9,
      height: 50,
      width: '80%'
    },
    loginHeader: {
      // position: 'relative',
      // bottom: '0%',
      marginTop: '2%',
      marginLeft: '10%',
      marginRight: '10%',
      backgroundColor: 'white',
      opacity: 0.9,
      justifyContent: 'center',
      alignItems: 'center',
      height: 50,
      width: '80%'
    },
    loginTitle: {
      position: 'absolute',
      bottom: '10%',
      // marginTop: '10%',
      // marginBottom: '10%',
      marginLeft: '5%',
      marginRight: '5%',
      // backgroundColor: 'white',
      // opacity: 0.75,
      textAlign: 'center',
      fontWeight: 'bold',
      fontSize: 16,
      color: "#505050",
    },
    createChefTitle: {
      position: 'absolute',
      bottom: '26%',
      // marginTop: '10%',
      // marginBottom: '10%',
      marginLeft: '5%',
      marginRight: '5%',
      // backgroundColor: 'white',
      // opacity: 0.75,
      textAlign: 'center',
      fontWeight: 'bold',
      fontSize: 16,
      color: "#505050",
    },
    loginFormButtonWrapper: {
      // borderStyle: 'solid',
      // borderWidth: 2,
      width: '100%',
      flex: 1,
      // flexWrap: 'wrap', 
      // alignItems: 'flex-start',
      flexDirection:'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    loginFormButton:{
      marginTop: '2%',
      marginLeft: '5%',
      marginRight: '5%',
      // position: 'relative',
      justifyContent: 'center',
      alignItems: 'center',
      // alignSelf: 'flex-start',
      width: '35%',
      height: 50,
      // flexDirection:'row',
      // backgroundColor: 'blue',
      // color: 'white'
      opacity: 0.9
    },
    floatingButton: {
        position: 'absolute',
        left: '81%',
        bottom: '3%',
        zIndex: 1,
        height: 50,
        width: 50,
        justifyContent: 'center',
      },
    standardButton: {
        height: 50,
        width: 50,
        justifyContent: 'center',
    },
    standardIcon: {
      color: "#505050"
    },
    submitButton: {
      fontSize: 10,
      justifyContent: 'center',
      alignItems: 'center',
      // backgroundColor: 'blue',
      // color: 'white'
    },
    createChefForm: {
      position: 'absolute',
      bottom: '10%',
      // borderStyle: 'solid',
      // borderWidth: 2,
      width: '100%'
    },
    createChefFormButton:{
      marginTop: '2%',
      marginLeft: '5%',
      marginRight: '5%',
      // position: 'relative',
      justifyContent: 'center',
      alignItems: 'center',
      // alignSelf: 'flex-start',
      width: '35%',
      height: 50,
      // flexDirection:'row',
      // backgroundColor: 'blue',
      // color: 'white'
      opacity: 0.9
    },
    createChefFormButtonText: {
      marginLeft: '5%',
      marginRight: '5%',
      // backgroundColor: 'white',
      // opacity: 0.75,
      textAlign: 'center',
      fontWeight: 'bold',
      fontSize: 14,
      color: "#505050",
    },
    createChefFormInputWrapper: {
      // borderStyle: 'solid',
      // borderWidth: 2,
      width: '100%',
      flex: 1,
      // flexWrap: 'wrap', 
      // alignItems: 'flex-start',
      flexDirection:'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    createChefInputBox: {
     // position: 'relative',
      // bottom: '0%',
      marginTop: '2%',
      marginLeft: '10%',
      marginRight: '10%',
      backgroundColor: 'white',
      opacity: 0.9,
      height: 50,
      width: '80%'
    },
    createRecipeForm: {
      // position: 'absolute',
      // bottom: '10%',
      // borderStyle: 'solid',
      // borderWidth: 2,
      // width: '100%'
    },
    createRecipeInputBox: {
      // position: 'relative',
       // bottom: '0%',
       marginTop: '2%',
       marginLeft: '10%',
       marginRight: '10%',
       backgroundColor: 'white',
       opacity: 0.9,
       height: 50,
       width: '80%'
     },
     createRecipeTextAreaBox: {
      // position: 'relative',
       // bottom: '0%',
       marginTop: '2%',
       marginLeft: '10%',
       marginRight: '10%',
       backgroundColor: 'white',
       opacity: 0.9,
       height: 150,
       width: '80%'
     },
     createRecipeTextAreaInput: {
       height: 130,
     },
     createRecipeFormButton:{
      marginTop: '2%',
      marginLeft: '5%',
      marginRight: '5%',
      // position: 'relative',
      justifyContent: 'center',
      alignItems: 'center',
      // alignSelf: 'flex-start',
      width: '35%',
      height: 50,
      // flexDirection:'row',
      // backgroundColor: 'blue',
      // color: 'white'
      opacity: 0.9
    },
    createRecipeFormSubmitButton:{
      marginTop: '2%',
      marginBottom: '2%',
      marginLeft: '5%',
      marginRight: '5%',
      // position: 'relative',
      justifyContent: 'center',
      alignItems: 'center',
      // alignSelf: 'flex-start',
      width: '35%',
      height: 50,
      // flexDirection:'row',
      // backgroundColor: 'blue',
      // color: 'white'
      opacity: 0.9
    },
    createRecipeFormButtonText: {
      marginLeft: '5%',
      marginRight: '5%',
      // backgroundColor: 'white',
      // opacity: 0.75,
      textAlign: 'center',
      fontWeight: 'bold',
      fontSize: 14,
      color: "#505050",
    },
    ingredientContainer: {
      // borderStyle: 'solid',
      // borderWidth: 2,
      width: '100%',
      flex: 1,
      // flexWrap: 'wrap', 
      // alignItems: 'flex-start',
      flexDirection:'row',
      // justifyContent: 'center',
      // alignItems: 'center',
    },
    addIngredientNameInputBox: {
      // position: 'relative',
       // bottom: '0%',
       marginTop: '2%',
       marginLeft: '2%',
       marginRight: '1%',
       backgroundColor: 'white',
       opacity: 0.9,
       height: 50,
       width: '48%'
    },
    addIngredientQuantityInputBox: {
      // position: 'relative',
       // bottom: '0%',
       marginTop: '2%',
      //  marginLeft: '1%',
      //  marginRight: '1%',
       backgroundColor: 'white',
       opacity: 0.9,
       height: 50,
       width: '18%'
    },
    addIngredientUnitInputBox: {
      // position: 'relative',
       // bottom: '0%',
       marginTop: '2%',
       marginLeft: '1%',
       marginRight: '2%',
       backgroundColor: 'white',
       opacity: 0.9,
       height: 50,
       width: '28%'
    },
    newRecipeTextCentering: {
      position: 'absolute',
    },
    QtyTextCentering: {
      position: 'absolute',
      left: '10%'
    },
    timeAndDifficultyWrapper: {
      // borderStyle: 'solid',
      // borderWidth: 2,
      // borderColor: 'white',
      width: '100%',
      // height: 50,
      flex: 1,
      // flexWrap: 'wrap', 
      // alignItems: 'flex-start',
      flexDirection:'row',
      justifyContent: 'center',
      // alignItems: 'center',
     },
    timeAndDifficulty: {
    //  position: 'absolute',
       // bottom: '0%',
       marginTop: '2%',
       marginLeft: '5%',
       marginRight: '5%',
       backgroundColor: 'white',
       opacity: 0.9,
       height: 50,
       width: '35%',
     },
     timeAndDifficultyTitleItem: {
      //  position: 'absolute',
         // bottom: '0%',
         marginTop: '2%',
         marginLeft: '5%',
         marginRight: '5%',
         backgroundColor: 'white',
         opacity: 0.9,
         height: 25,
         width: '35%',
         justifyContent: 'center',
       },
     timeAndDifficultyTitle: {
      position: 'absolute',
      bottom: '5%',
      // marginTop: '10%',
      // marginBottom: '10%',
      marginLeft: '5%',
      marginRight: '5%',
      // backgroundColor: 'white',
      // opacity: 0.75,
      // textAlign: 'center',
      // fontWeight: 'bold',
      fontSize: 16,
      color: "#505050",
      },
    picker: {
      margin: '15%',
      // position: 'absolute',
      bottom: '2%',
      // marginTop: '10%',
      // marginBottom: '10%',
      // marginLeft: '5%',
      // marginRight: '5%',
      // backgroundColor: 'white',
      // opacity: 0.75,
      // textAlign: 'center',
      // fontWeight: 'bold',
      // fontSize: 26,
      color: "#505050",
      // height: 100
      
    },
    unitPicker: {
      margin: '5%',
      bottom: '2%',

    },
  });