entrypoint: bundle exec rails s -p 8080 -e production
env: flex
runtime: ruby

env_variables:
  SECRET_KEY_BASE: <%= Rails.application.credentials[:secret_key_base] %>

beta_settings:
  cloud_sql_instances: recipe-share-269804:us-central1:recipe-share