entrypoint: bundle exec rails s -p 8080 -e production
env: flex
runtime: ruby

env_variables:
  SECRET_KEY_BASE: <%= Rails.application.credentials[:secret_key_base] %>

beta_settings:
  cloud_sql_instances: "recipe-share-272202:us-central1:recipe-share"

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 15