source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.3"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "rails", "~> 5.2.3"
# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.3.6"
# Use Puma as the app server
# gem 'puma', '~> 3.11'
gem "puma", "~> 4.3"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
gem "bcrypt", "~> 3.1.7"

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'
# gem 'activestorage', ">= 5.2.4.3"

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.1.0", require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem "rack-cors"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "rspec-rails", "~> 4.0.0"
end

group :development do
  gem "listen", ">= 3.0.5", "< 3.2"
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem "faker", :git => "https://github.com/stympy/faker.git", :branch => "master"
gem "jwt"
gem "rb-readline"
gem "rubocop"
gem "solargraph"
gem "google-cloud-storage"
gem "pg", "~> 1.2"

gem "app", "~> 1.2"

gem "appengine", "~> 0.5.0"
gem "email_validator"
gem "rufo"
gem "validate_url"

# git hub security alerts
# gem "activesupport", ">= 5.2.4.3"
# gem "actionview", ">= 5.2.4.4"
# gem "actionpack", ">= 5.2.4.3"

# rails generate rspec:model application_record
# rails generate rspec:model chef
# rails generate rspec:model comment
# rails generate rspec:model database
# rails generate rspec:model follow
# rails generate rspec:model friendship
# rails generate rspec:model ingredient_use
# rails generate rspec:model ingredient
# rails generate rspec:model instruction_image
# rails generate rspec:model instruction
# rails generate rspec:model make_pic
# rails generate rspec:model re_share
# rails generate rspec:model recipe_image
# rails generate rspec:model recipe_like
# rails generate rspec:model recipe_make
# rails generate rspec:model recipe
# rails generate rspec:controller application_controller
# rails generate rspec:controller chefs_controller
# rails generate rspec:controller comments_controller
# rails generate rspec:controller databases_controller
# rails generate rspec:controller follows_controller
# rails generate rspec:controller friendships_controller
# rails generate rspec:controller ingredient_uses_controller
# rails generate rspec:controller ingredients_controller
# rails generate rspec:controller instruction_images_controller
# rails generate rspec:controller instructions_controller
# rails generate rspec:controller make_pics_controller
# rails generate rspec:controller re_shares_controller
# rails generate rspec:controller recipe_images_controller
# rails generate rspec:controller recipe_likes_controller
# rails generate rspec:controller recipe_makes_controller
# rails generate rspec:controller recipes_controller

# rails generate rspec:scaffold chefs_controller
