export const listProps = [
	{
		"testTitle": "default",
		"chef_commented": 2,
		"chef_liked": 1,
		"chef_made": 0,
		"chef_shared": 0,
		"chefimage_url": "",
		"comments_count": 2,
		"difficulty": 4,
		"id": 306,
		"image_url": null,
		"likes_count": 1,
		"makes_count": 0,
		"name": "Test recipe",
		"renderOfflineMessage": [],
		"shared_id": 306,
		"sharer_id": 97,
		"sharer_username": "pothers",
		"shares_count": 1,
		"time": "01:00",
		"username": "pothers",
	},
	{
		"testTitle": "longStrings",
		"chef_commented": 2,
		"chef_liked": 1,
		"chef_made": 0,
		"chef_shared": 0,
		"chefimage_url": "",
		"comments_count": 2,
		"difficulty": 4,
		"id": 307,
		"image_url": null,
		"likes_count": 1,
		"makes_count": 0,
		"name": "This is my test recipe with a really long title and I want to know that it renders properly when the title string is really long.",
		"renderOfflineMessage": [],
		"shared_id": 306,
		"sharer_id": 97,
		"sharer_username": "pothers",
		"shares_count": 1,
		"time": "01:00",
		"username": "pothers",
	},
]

