export const listProps = [
	{
		"acknowledgement": "Creamy mascarpone cheese and custard layered between espresso and rum soaked house-made ladyfingers, topped with Valrhona cocoa powder.",
		"bread": false,
		"breakfast": false,
		"chef_commented": 0,
		"chef_id": 12,
		"chef_liked": 0,
		"chef_made": 0,
		"chef_shared": 0,
		"chefimage_url": "https://storage.googleapis.com/download/storage/v1/b/chef-avatars-ac1cff8d11c908f3cf8613121b61683221152250/o/59b9a3ad9aaf1fe5f9fd5c92c62461eaa88fea89.jpg?generation=1601673323651524&alt=media",
		"chicken": true,
		"comments_count": 4,
		"created_at": "2020-10-02T19:09:33.552Z",
		"cuisine": "Turkish",
		"dairy_free": false,
		"description": "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits.",
		"dessert": true,
		"difficulty": 6,
		"dinner": false,
		"freezer_meal": true,
		"gluten_free": false,
		"hidden": false,
		"id": 250,
		"image_url": null,
		"keto": false,
		"likes_count": 3,
		"listChoice": "chef",
		"lunch": false,
		"makes_count": 1,
		"name": "Recipe with no cover images - TEST:NORMAL",
		"paleo": true,
		"red_meat": true,
		"renderOfflineMessage": [],
		"salad": true,
		"seafood": false,
		"serves": "3",
		"shares_count": 2,
		"side": true,
		"soup": false,
		"time": "06:00",
		"updated_at": "2020-10-02T22:07:27.075Z",
		"username": "pothers",
		"vegan": true,
		"vegetarian": true,
		"weekend": false,
		"weeknight": false,
		"white_meat": false,
		"whole_30": true,
	},
	{
		"acknowledgement": "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant.",
		"bread": false,
		"breakfast": false,
		"chef_commented": 0,
		"chef_id": 3,
		"chef_liked": 1,
		"chef_made": 0,
		"chef_shared": 0,
		"chefimage_url": "https://robohash.org/architectoquidemqui.png?size=300x300&set=set1",
		"chicken": true,
		"comments_count": 5,
		"created_at": "2020-10-02T19:09:33.291Z",
		"cuisine": "Vietnamese",
		"dairy_free": false,
		"description": "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes.",
		"dessert": true,
		"difficulty": 8,
		"dinner": true,
		"freezer_meal": false,
		"gluten_free": true,
		"hidden": false,
		"id": 249,
		"image_url": "https://storage.googleapis.com/test-images-be4d3e05-1e77-4efd-8571-364e22ea7c0d/recipe55.jpg",
		"keto": true,
		"last_update": "2020-10-04T16:24:51.646Z",
		"likes_count": 6,
		"listChoice": "chef_liked",
		"lunch": false,
		"makes_count": 2,
		"name": "Massaman Curry - TEST:LIKED",
		"paleo": true,
		"red_meat": false,
		"renderOfflineMessage": [],
		"salad": false,
		"seafood": true,
		"serves": "10",
		"shares_count": 0,
		"side": false,
		"soup": true,
		"time": "02:30",
		"updated_at": "2020-10-02T19:09:33.408Z",
		"username": "Sichult",
		"vegan": true,
		"vegetarian": true,
		"weekend": true,
		"weeknight": true,
		"white_meat": true,
		"whole_30": false,
	},
	{
		"acknowledgement": "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant.",
		"bread": false,
		"breakfast": false,
		"chef_commented": 0,
		"chef_id": 3,
		"chef_liked": 1,
		"chef_made": 0,
		"chef_shared": 1,
		"chefimage_url": "https://robohash.org/architectoquidemqui.png?size=300x300&set=set1",
		"chicken": true,
		"comments_count": 5,
		"created_at": "2020-10-02T19:09:33.291Z",
		"cuisine": "Vietnamese",
		"dairy_free": false,
		"description": "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes.",
		"dessert": true,
		"difficulty": 8,
		"dinner": true,
		"freezer_meal": false,
		"gluten_free": true,
		"hidden": false,
		"id": 249,
		"image_url": "https://storage.googleapis.com/test-images-be4d3e05-1e77-4efd-8571-364e22ea7c0d/recipe55.jpg",
		"keto": true,
		"last_update": "2020-10-04T16:26:53.067Z",
		"likes_count": 6,
		"listChoice": "chef_liked",
		"lunch": false,
		"makes_count": 2,
		"name": "Massaman Curry - TEST:SHARED",
		"paleo": true,
		"red_meat": false,
		"renderOfflineMessage": [],
		"salad": false,
		"seafood": true,
		"serves": "10",
		"shares_count": 1,
		"side": false,
		"soup": true,
		"time": "02:30",
		"updated_at": "2020-10-02T19:09:33.408Z",
		"username": "Sichult",
		"vegan": true,
		"vegetarian": true,
		"weekend": true,
		"weeknight": true,
		"white_meat": true,
		"whole_30": false,
	},
	{
		"acknowledgement": "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream.",
		"bread": false,
		"breakfast": false,
		"chef_commented": 1,
		"chef_id": 2,
		"chef_liked": 1,
		"chef_made": 0,
		"chef_shared": 0,
		"chefimage_url": "https://robohash.org/ablaudantiumaut.png?size=300x300&set=set1",
		"chicken": false,
		"comments_count": 4,
		"created_at": "2020-10-02T19:09:32.350Z",
		"cuisine": "German",
		"dairy_free": false,
		"description": "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits.",
		"dessert": true,
		"difficulty": 4,
		"dinner": true,
		"freezer_meal": true,
		"gluten_free": true,
		"hidden": false,
		"id": 245,
		"image_url": "https://storage.googleapis.com/test-images-be4d3e05-1e77-4efd-8571-364e22ea7c0d/recipe56.jpg",
		"keto": true,
		"last_update": "2020-10-04T16:27:51.665Z",
		"likes_count": 6,
		"listChoice": "chef_liked",
		"lunch": false,
		"makes_count": 2,
		"name": "Chicken Fajitas - TEST:COMMENTED",
		"paleo": false,
		"red_meat": false,
		"renderOfflineMessage": [],
		"salad": false,
		"seafood": true,
		"serves": "1",
		"shares_count": 1,
		"side": false,
		"soup": false,
		"time": "02:45",
		"updated_at": "2020-10-02T19:09:32.441Z",
		"username": "Chel",
		"vegan": false,
		"vegetarian": false,
		"weekend": false,
		"weeknight": true,
		"white_meat": true,
		"whole_30": false,
	},
	{
		"acknowledgement": "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream.",
		"bread": false,
		"breakfast": false,
		"chef_commented": 1,
		"chef_id": 2,
		"chef_liked": 1,
		"chef_made": 0,
		"chef_shared": 1,
		"chefimage_url": "https://robohash.org/ablaudantiumaut.png?size=300x300&set=set1",
		"chicken": false,
		"comments_count": 4,
		"created_at": "2020-10-02T19:09:32.350Z",
		"cuisine": "German",
		"dairy_free": false,
		"description": "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits.",
		"dessert": true,
		"difficulty": 4,
		"dinner": true,
		"freezer_meal": true,
		"gluten_free": true,
		"hidden": false,
		"id": 245,
		"image_url": "https://storage.googleapis.com/test-images-be4d3e05-1e77-4efd-8571-364e22ea7c0d/recipe56.jpg",
		"keto": true,
		"last_update": "2020-10-04T16:27:51.665Z",
		"likes_count": 6,
		"listChoice": "chef_liked",
		"lunch": false,
		"makes_count": 2,
		"name": "Chicken Fajitas - TEST:ALL",
		"paleo": false,
		"red_meat": false,
		"renderOfflineMessage": [],
		"salad": false,
		"seafood": true,
		"serves": "1",
		"shares_count": 2,
		"side": false,
		"soup": false,
		"time": "02:45",
		"updated_at": "2020-10-02T19:09:32.441Z",
		"username": "Chel",
		"vegan": false,
		"vegetarian": false,
		"weekend": false,
		"weeknight": true,
		"white_meat": true,
		"whole_30": false,
	},
	{
		"acknowledgement": "Breaded fried chicken with waffles, and a side of maple syrup.",
		"bread": true,
		"breakfast": true,
		"chef_commented": 0,
		"chef_id": 12,
		"chef_liked": 1,
		"chef_made": 0,
		"chef_shared": 0,
		"chefimage_url": "https://storage.googleapis.com/download/storage/v1/b/chef-avatars-ac1cff8d11c908f3cf8613121b61683221152250/o/59b9a3ad9aaf1fe5f9fd5c92c62461eaa88fea89.jpg?generation=1601673323651524&alt=media",
		"chicken": false,
		"comments_count": 0,
		"created_at": "2020-10-02T19:09:32.816Z",
		"cuisine": "Japanese",
		"dairy_free": false,
		"description": "Two buttermilk waffles, topped with whipped cream and maple syrup, a side of two eggs served any style, and your choice of smoked bacon or smoked ham.",
		"dessert": true,
		"difficulty": 5,
		"dinner": false,
		"freezer_meal": false,
		"gluten_free": false,
		"hidden": false,
		"id": 247,
		"image_url": "https://storage.googleapis.com/test-images-be4d3e05-1e77-4efd-8571-364e22ea7c0d/recipe16.jpg",
		"keto": true,
		"last_update": "2020-10-04T16:33:32.335Z",
		"likes_count": 5,
		"listChoice": "chef_liked",
		"lunch": false,
		"makes_count": 0,
		"name": "Recipe name with a really long name that would cover more than one line, and possibly even a couple of lines purely for the sake of seeing how it affects the ui - TEST:LONGRECIPENAME",
		"paleo": false,
		"red_meat": true,
		"renderOfflineMessage": [],
		"salad": true,
		"seafood": false,
		"serves": "2",
		"shares_count": 0,
		"side": false,
		"soup": false,
		"time": "01:45",
		"updated_at": "2020-10-02T22:00:11.741Z",
		"username": "pothers",
		"vegan": true,
		"vegetarian": true,
		"weekend": true,
		"weeknight": true,
		"white_meat": true,
		"whole_30": true,
	},
	{
		"acknowledgement": "Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides.",
		"bread": true,
		"breakfast": true,
		"chef_commented": 0,
		"chef_id": 12,
		"chef_liked": 1,
		"chef_made": 0,
		"chef_shared": 0,
		"chefimage_url": "https://storage.googleapis.com/download/storage/v1/b/chef-avatars-ac1cff8d11c908f3cf8613121b61683221152250/o/59b9a3ad9aaf1fe5f9fd5c92c62461eaa88fea89.jpg?generation=1601673323651524&alt=media",
		"chicken": true,
		"comments_count": 3,
		"created_at": "2020-10-02T19:09:29.599Z",
		"cuisine": "Vietnamese",
		"dairy_free": true,
		"description": "Breaded fried chicken with waffles. Served with maple syrup.",
		"dessert": false,
		"difficulty": 2,
		"dinner": true,
		"freezer_meal": true,
		"gluten_free": false,
		"hidden": false,
		"id": 234,
		"image_url": null,
		"keto": false,
		"last_update": "2020-10-04T16:35:46.607Z",
		"likes_count": 6,
		"listChoice": "chef_liked",
		"lunch": true,
		"makes_count": 2,
		"name": "Caprese Salad - TEST:NOCOVERIMAGE",
		"paleo": true,
		"red_meat": true,
		"renderOfflineMessage": [],
		"salad": false,
		"seafood": true,
		"serves": "Any",
		"shares_count": 0,
		"side": true,
		"soup": true,
		"time": "01:00",
		"updated_at": "2020-10-04T16:35:30.193Z",
		"username": "pothers",
		"vegan": false,
		"vegetarian": true,
		"weekend": true,
		"weeknight": true,
		"white_meat": false,
		"whole_30": true,
	},
	{
		"acknowledgement": "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant.",
		"bread": false,
		"breakfast": false,
		"chef_commented": 0,
		"chef_id": 3,
		"chef_liked": 0,
		"chef_made": 0,
		"chef_shared": 1,
		"chefimage_url": "https://robohash.org/architectoquidemqui.png?size=300x300&set=set1",
		"chicken": true,
		"comments_count": 5,
		"created_at": "2020-10-02T19:09:33.291Z",
		"cuisine": "Vietnamese",
		"dairy_free": false,
		"description": "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes.",
		"dessert": true,
		"difficulty": 8,
		"dinner": true,
		"freezer_meal": false,
		"gluten_free": true,
		"hidden": false,
		"id": 249,
		"image_url": "https://storage.googleapis.com/test-images-be4d3e05-1e77-4efd-8571-364e22ea7c0d/recipe55.jpg",
		"keto": true,
		"likes_count": 5,
		"listChoice": "chef_feed",
		"lunch": false,
		"makes_count": 2,
		"name": "Massaman Curry - TEST:RESHAREDBY",
		"paleo": true,
		"red_meat": false,
		"renderOfflineMessage": [],
		"salad": false,
		"seafood": true,
		"serves": "10",
		"shared_id": 249,
		"sharer_id": 12,
		"sharer_username": "pothers",
		"shares_count": 1,
		"side": false,
		"soup": true,
		"time": "02:30",
		"updated_at": "2020-10-02T19:09:33.408Z",
		"username": "Sichult",
		"vegan": true,
		"vegetarian": true,
		"weekend": true,
		"weeknight": true,
		"white_meat": true,
		"whole_30": false,
	},
	{
		"acknowledgement": "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits.",
		"bread": false,
		"breakfast": true,
		"chef_commented": 0,
		"chef_id": 1,
		"chef_liked": 1,
		"chef_made": 0,
		"chef_shared": 0,
		"chefimage_url": "",
		"chicken": true,
		"comments_count": 3,
		"created_at": "2020-10-02T19:09:29.842Z",
		"cuisine": "Mediterranean",
		"dairy_free": true,
		"description": "Two buttermilk waffles, topped with whipped cream and maple syrup, a side of two eggs served any style, and your choice of smoked bacon or smoked ham.",
		"dessert": true,
		"difficulty": 7,
		"dinner": true,
		"freezer_meal": false,
		"gluten_free": true,
		"hidden": false,
		"id": 235,
		"image_url": "https://storage.googleapis.com/test-images-be4d3e05-1e77-4efd-8571-364e22ea7c0d/recipe13.jpg",
		"keto": true,
		"last_update": "2020-10-04T16:39:43.164Z",
		"likes_count": 4,
		"listChoice": "chef_liked",
		"lunch": true,
		"makes_count": 2,
		"name": "Ebiten maki - TEST:NOCHEFIMAGE",
		"paleo": false,
		"red_meat": false,
		"renderOfflineMessage": [],
		"salad": false,
		"seafood": false,
		"serves": "9",
		"shares_count": 0,
		"side": false,
		"soup": false,
		"time": "03:45",
		"updated_at": "2020-10-02T19:09:29.948Z",
		"username": "Anonymous",
		"vegan": false,
		"vegetarian": false,
		"weekend": true,
		"weeknight": true,
		"white_meat": true,
		"whole_30": false,
	},
	{
		"acknowledgement": "Two butter croissants of your choice (plain, almond or cheese). With a side of herb butter or house-made hazelnut spread.",
		"bread": true,
		"breakfast": true,
		"chef_commented": 0,
		"chef_id": 9,
		"chef_liked": 1,
		"chef_made": 0,
		"chef_shared": 0,
		"chefimage_url": "https://robohash.org/autquiaut.png?size=300x300&set=set1",
		"chicken": false,
		"comments_count": 1,
		"created_at": "2020-10-02T19:09:31.313Z",
		"cuisine": "Spanish",
		"dairy_free": false,
		"description": "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream.",
		"dessert": true,
		"difficulty": 5,
		"dinner": false,
		"freezer_meal": false,
		"gluten_free": true,
		"hidden": false,
		"id": 241,
		"image_url": "https://storage.googleapis.com/test-images-be4d3e05-1e77-4efd-8571-364e22ea7c0d/recipe39.jpg",
		"keto": true,
		"last_update": "2020-10-04T16:56:45.133Z",
		"likes_count": 3,
		"listChoice": "chef_liked",
		"lunch": false,
		"makes_count": 3,
		"name": "Poutine - TEST:NORMAL2",
		"paleo": false,
		"red_meat": false,
		"renderOfflineMessage": [],
		"salad": false,
		"seafood": true,
		"serves": "8",
		"shares_count": 1,
		"side": false,
		"soup": false,
		"time": "04:15",
		"updated_at": "2020-10-02T19:09:31.430Z",
		"username": "Xinth",
		"vegan": false,
		"vegetarian": false,
		"weekend": false,
		"weeknight": false,
		"white_meat": false,
		"whole_30": true,
	},
	{
		"acknowledgement": "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream.",
		"bread": true,
		"breakfast": false,
		"chef_commented": 0,
		"chef_id": 3,
		"chef_liked": 1,
		"chef_made": 0,
		"chef_shared": 0,
		"chefimage_url": "https://robohash.org/architectoquidemqui.png?size=300x300&set=set1",
		"chicken": false,
		"comments_count": 2,
		"created_at": "2020-10-02T19:09:31.571Z",
		"cuisine": "Greek",
		"dairy_free": false,
		"description": "Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides.",
		"dessert": false,
		"difficulty": 9,
		"dinner": false,
		"freezer_meal": true,
		"gluten_free": true,
		"hidden": false,
		"id": 242,
		"image_url": "https://storage.googleapis.com/test-images-be4d3e05-1e77-4efd-8571-364e22ea7c0d/recipe14.jpg",
		"keto": true,
		"last_update": "2020-10-04T16:56:41.843Z",
		"likes_count": 4,
		"listChoice": "chef_liked",
		"lunch": false,
		"makes_count": 3,
		"name": "Linguine with Clams - TEST:NORMAL3",
		"paleo": false,
		"red_meat": false,
		"renderOfflineMessage": [],
		"salad": true,
		"seafood": false,
		"serves": "9",
		"shares_count": 1,
		"side": true,
		"soup": false,
		"time": "04:30",
		"updated_at": "2020-10-02T19:09:31.663Z",
		"username": "Sichult",
		"vegan": false,
		"vegetarian": true,
		"weekend": false,
		"weeknight": true,
		"white_meat": false,
		"whole_30": true,
	},
	{
		"acknowledgement": "Breaded fried chicken with waffles, and a side of maple syrup.",
		"bread": false,
		"breakfast": false,
		"chef_commented": 0,
		"chef_id": 12,
		"chef_liked": 1,
		"chef_made": 0,
		"chef_shared": 0,
		"chefimage_url": "https://storage.googleapis.com/download/storage/v1/b/chef-avatars-ac1cff8d11c908f3cf8613121b61683221152250/o/59b9a3ad9aaf1fe5f9fd5c92c62461eaa88fea89.jpg?generation=1601673323651524&alt=media",
		"chicken": true,
		"comments_count": 1,
		"created_at": "2020-10-02T19:09:26.503Z",
		"cuisine": "Vietnamese",
		"dairy_free": true,
		"description": "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes.",
		"dessert": true,
		"difficulty": 6,
		"dinner": true,
		"freezer_meal": true,
		"gluten_free": true,
		"hidden": false,
		"id": 221,
		"image_url": "https://storage.googleapis.com/test-images-be4d3e05-1e77-4efd-8571-364e22ea7c0d/recipe6.jpg",
		"keto": false,
		"likes_count": 5,
		"listChoice": "chef",
		"lunch": false,
		"makes_count": 3,
		"name": "Spaghetti bolognaise - TEST:LONGUSERNAME",
		"paleo": true,
		"red_meat": false,
		"renderOfflineMessage": [],
		"salad": true,
		"seafood": true,
		"serves": "9",
		"shares_count": 0,
		"side": true,
		"soup": true,
		"time": "01:00",
		"updated_at": "2020-10-04T16:08:59.287Z",
		"username": "I have a ridiculously long username just for testing how the UI handles it - TEST:LONGUSERNAME",
		"vegan": true,
		"vegetarian": false,
		"weekend": true,
		"weeknight": false,
		"white_meat": false,
		"whole_30": true,
	},
	{
		"acknowledgement": "Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides.",
		"bread": true,
		"breakfast": true,
		"chef_commented": 0,
		"chef_id": 12,
		"chef_liked": 1,
		"chef_made": 0,
		"chef_shared": 1,
		"chefimage_url": "https://storage.googleapis.com/download/storage/v1/b/chef-avatars-ac1cff8d11c908f3cf8613121b61683221152250/o/59b9a3ad9aaf1fe5f9fd5c92c62461eaa88fea89.jpg?generation=1601673323651524&alt=media",
		"chicken": true,
		"comments_count": 3,
		"created_at": "2020-10-02T19:09:29.599Z",
		"cuisine": "Vietnamese",
		"dairy_free": true,
		"description": "Breaded fried chicken with waffles. Served with maple syrup.",
		"dessert": false,
		"difficulty": 2,
		"dinner": true,
		"freezer_meal": true,
		"gluten_free": false,
		"hidden": false,
		"id": 234,
		"image_url": null,
		"keto": false,
		"likes_count": 6,
		"listChoice": "chef_feed",
		"lunch": true,
		"makes_count": 2,
		"name": "Caprese Salad - TEST:LONGRESHARERUSERNAME",
		"paleo": true,
		"red_meat": true,
		"renderOfflineMessage": [],
		"salad": false,
		"seafood": true,
		"serves": "Any",
		"shared_id": 234,
		"sharer_id": 12,
		"sharer_username": "I have a ridiculously long username just for testing how the UI handles it",
		"shares_count": 1,
		"side": true,
		"soup": true,
		"time": "01:00",
		"updated_at": "2020-10-04T16:35:30.193Z",
		"username": "I have a ridiculously long username just for testing how the UI handles it",
		"vegan": false,
		"vegetarian": true,
		"weekend": true,
		"weeknight": true,
		"white_meat": false,
		"whole_30": true,
	},
	{
		"acknowledgement": "Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides.",
		"bread": true,
		"breakfast": false,
		"chef_commented": 0,
		"chef_id": 2,
		"chef_liked": 1,
		"chef_made": 0,
		"chef_shared": 0,
		"chefimage_url": "https://robohash.org/ablaudantiumaut.png?size=300x300&set=set1",
		"chicken": true,
		"comments_count": 2,
		"created_at": "2020-10-02T19:09:28.885Z",
		"cuisine": "Egyptian",
		"dairy_free": true,
		"description": "Creamy mascarpone cheese and custard layered between espresso and rum soaked house-made ladyfingers, topped with Valrhona cocoa powder.",
		"dessert": true,
		"difficulty": 10,
		"dinner": false,
		"freezer_meal": false,
		"gluten_free": false,
		"hidden": false,
		"id": 231,
		"image_url": "https://storage.googleapis.com/test-images-be4d3e05-1e77-4efd-8571-364e22ea7c0d/recipe2.jpg",
		"keto": true,
		"last_update": "2020-10-04T16:56:53.812Z",
		"likes_count": 5,
		"listChoice": "chef_liked",
		"lunch": false,
		"makes_count": 0,
		"name": "Bruschette with Tomato - TEST:NORMAL6",
		"paleo": true,
		"red_meat": false,
		"renderOfflineMessage": [],
		"salad": true,
		"seafood": true,
		"serves": "10",
		"shares_count": 0,
		"side": true,
		"soup": true,
		"time": "03:45",
		"updated_at": "2020-10-02T19:09:28.983Z",
		"username": "Chel",
		"vegan": true,
		"vegetarian": false,
		"weekend": false,
		"weeknight": false,
		"white_meat": true,
		"whole_30": true,
	},
	{
		"acknowledgement": "Two buttermilk waffles, topped with whipped cream and maple syrup, a side of two eggs served any style, and your choice of smoked bacon or smoked ham.",
		"bread": true,
		"breakfast": false,
		"chef_commented": 0,
		"chef_id": 3,
		"chef_liked": 1,
		"chef_made": 0,
		"chef_shared": 0,
		"chefimage_url": "https://robohash.org/architectoquidemqui.png?size=300x300&set=set1",
		"chicken": true,
		"comments_count": 3,
		"created_at": "2020-10-02T19:09:29.131Z",
		"cuisine": "Swedish",
		"dairy_free": false,
		"description": "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant.",
		"dessert": true,
		"difficulty": 9,
		"dinner": false,
		"freezer_meal": false,
		"gluten_free": false,
		"hidden": false,
		"id": 232,
		"image_url": "https://storage.googleapis.com/test-images-be4d3e05-1e77-4efd-8571-364e22ea7c0d/recipe17.jpg",
		"keto": false,
		"last_update": "2020-10-04T16:56:51.526Z",
		"likes_count": 7,
		"listChoice": "chef_liked",
		"lunch": true,
		"makes_count": 1,
		"name": "Pho - TEST:NORMAL5",
		"paleo": true,
		"red_meat": false,
		"renderOfflineMessage": [],
		"salad": true,
		"seafood": true,
		"serves": "6",
		"shares_count": 0,
		"side": true,
		"soup": false,
		"time": "05:00",
		"updated_at": "2020-10-02T19:09:29.225Z",
		"username": "Sichult",
		"vegan": false,
		"vegetarian": true,
		"weekend": false,
		"weeknight": true,
		"white_meat": false,
		"whole_30": false,
	},
	{
		"acknowledgement": "28-day aged 300g USDA Certified Prime Ribeye, rosemary-thyme garlic butter, with choice of two sides.",
		"bread": false,
		"breakfast": true,
		"chef_commented": 0,
		"chef_id": 8,
		"chef_liked": 1,
		"chef_made": 0,
		"chef_shared": 0,
		"chefimage_url": "https://robohash.org/sedsuntsit.png?size=300x300&set=set1",
		"chicken": true,
		"comments_count": 1,
		"created_at": "2020-10-02T19:09:30.580Z",
		"cuisine": "Cuban",
		"dairy_free": true,
		"description": "28-day aged 300g USDA Certified Prime Ribeye, rosemary-thyme garlic butter, with choice of two sides.",
		"dessert": false,
		"difficulty": 7,
		"dinner": true,
		"freezer_meal": true,
		"gluten_free": false,
		"hidden": false,
		"id": 238,
		"image_url": "https://storage.googleapis.com/test-images-be4d3e05-1e77-4efd-8571-364e22ea7c0d/recipe15.jpg",
		"keto": true,
		"last_update": "2020-10-04T16:56:47.787Z",
		"likes_count": 5,
		"listChoice": "chef_liked",
		"lunch": true,
		"makes_count": 2,
		"name": "Pappardelle alla Bolognese - TEST:NORMAL4",
		"paleo": true,
		"red_meat": true,
		"renderOfflineMessage": [],
		"salad": false,
		"seafood": false,
		"serves": "2",
		"shares_count": 2,
		"side": false,
		"soup": true,
		"time": "03:30",
		"updated_at": "2020-10-02T19:09:30.679Z",
		"username": "Narisca",
		"vegan": true,
		"vegetarian": true,
		"weekend": true,
		"weeknight": true,
		"white_meat": true,
		"whole_30": false,
	},
]


