import React from 'react'
import { StyleSheet } from 'react-native';
import { responsiveHeight, responsiveWidth, responsiveFontSize } from 'react-native-responsive-dimensions'

export const styles = StyleSheet.create({
  modalFullScreenContainer:{
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  picChooserModalContainer:{
    // position: 'absolute',
    marginLeft: responsiveWidth(6.5),
    marginRight: responsiveWidth(6.5),
    // top: '25%',
    // height: responsiveHeight(90),
    minWidth: responsiveWidth(87),
    backgroundColor: 'white',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#104e01',
  },
  picSourceChooserImage:{
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: responsiveWidth(80),
    height: responsiveHeight(34),
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(3.5),
    marginRight: responsiveWidth(3.5),
    flexDirection:'row',
    borderRadius: 5,
    backgroundColor: 'white',
    borderStyle: 'solid',
    borderWidth: 1,
  },
    picSourceChooserButton:{
      justifyContent: 'center',
      alignItems: 'center',
      minWidth: responsiveWidth(80),
      marginLeft: responsiveWidth(3.5),
      marginRight: responsiveWidth(3.5),
      height: responsiveHeight(8),
      marginTop: responsiveHeight(0.5),
      flexDirection:'row',
      borderRadius: 5,
      backgroundColor: '#fff59b',
      borderStyle: 'solid',
      borderWidth: 1,
      borderColor: '#104e01',
    },
    picSourceChooserCancelButton:{
      justifyContent: 'center',
      alignItems: 'center',
      minWidth: responsiveWidth(80),
      marginLeft: responsiveWidth(3.5),
      marginRight: responsiveWidth(3.5),
      height: responsiveHeight(8),
      marginBottom: responsiveHeight(2),
      marginTop: responsiveHeight(0.5),
      flexDirection:'row',
      borderRadius: 5,
      backgroundColor: '#104e01',// red'#720000',
      borderStyle: 'solid',
      borderWidth: 1,
      borderColor: '#fff59b',
    },
    picSourceChooserButtonText: {
      marginLeft: '5%',
      marginRight: '5%',
      textAlign: 'center',
      fontWeight: 'bold',
      fontSize: responsiveFontSize(3),
      color: '#104e01',
    },
    standardIcon: {
      color: '#104e01',
    },
    cancelIcon: {
      color: '#fff29b',
    },
    picSourceChooserCancelButtonText: {
      marginLeft: '10%',
      marginRight: '5%',
      textAlign: 'center',
      fontWeight: 'bold',
      fontSize: responsiveFontSize(3),
      color: '#fff59b',
    },
  });