import { StyleSheet } from 'react-native';
import { responsiveWidth, responsiveHeight, responsiveFontSize } from 'react-native-responsive-dimensions'; //eslint-disable-line no-unused-vars

export const styles = StyleSheet.create({
	modalFullScreenContainer: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
	},
	picChooserModalContainer: {
		// position: 'absolute',
		marginLeft: responsiveWidth(6.5),
		marginRight: responsiveWidth(6.5),
		// top: '25%',
		// height: responsiveHeight(90),
		minWidth: responsiveWidth(87),
		backgroundColor: 'white',
		borderRadius: 5,
		borderWidth: 1,
		borderColor: '#104e01',
	},
	picSourceChooserImage: {
		justifyContent: 'center',
		alignItems: 'center',
		width: responsiveWidth(80),
		height: responsiveHeight(34),
		marginTop: responsiveHeight(2),
		marginLeft: responsiveWidth(3.5),
		marginRight: responsiveWidth(3.5),
		// flexDirection: 'row',
		borderRadius: 5,
		// backgroundColor: 'white',
		borderStyle: 'solid',
		borderWidth: 1,
		overflow: 'hidden',
		borderColor: '#104e01'
	},
	picSourceChooserButton: {
		justifyContent: 'center',
		alignItems: 'center',
		minWidth: responsiveWidth(80),
		marginLeft: responsiveWidth(3.5),
		marginRight: responsiveWidth(3.5),
		height: responsiveHeight(8),
		marginTop: responsiveHeight(0.5),
		flexDirection: 'row',
		borderRadius: 5,
		backgroundColor: '#fff59b',
		borderStyle: 'solid',
		borderWidth: 1,
		borderColor: '#104e01',
	},
	picSourceChooserArrowButtonContainer: {
		flexDirection: 'row',
		width: responsiveWidth(80),
		alignSelf: 'center',
		justifyContent: 'space-between'
	},
	picSourceChooserArrowButton: {
		justifyContent: 'center',
		alignItems: 'center',
		width: responsiveWidth(39.5),
		minHeight: responsiveHeight(8),
		marginTop: responsiveHeight(0.5),
		flexDirection: 'row',
		borderRadius: 5,
		backgroundColor: '#fff59b',
		borderStyle: 'solid',
		borderWidth: 1,
		borderColor: '#104e01',
	},
	picSourceChooserCancelButton: {
		justifyContent: 'center',
		alignItems: 'center',
		width: responsiveWidth(39.5),
		minHeight: responsiveHeight(8),
		marginTop: responsiveHeight(0.5),
		flexDirection: 'row',
		borderRadius: 5,
		borderStyle: 'solid',
		borderWidth: 1,
		backgroundColor: '#104e01',// red'#720000',
		borderColor: '#fff59b',
	},
	picSourceChooserButtonText: {
		marginLeft: '5%',
		marginRight: '5%',
		textAlign: 'center',
		fontWeight: 'bold',
		fontSize: responsiveFontSize(2.25),
		color: '#104e01',
		// flexWrap: 'wrap',
		// borderWidth: 1,
		// maxWidth: responsiveWidth(25)
	},
	standardIcon: {
		color: '#104e01',
	},
	cancelIcon: {
		color: '#fff59b',
	},
	picSourceChooserCancelButtonText: {
		marginLeft: '10%',
		marginRight: '5%',
		textAlign: 'center',
		fontWeight: 'bold',
		fontSize: responsiveFontSize(2.25),
		color: '#fff59b',
	},
	primaryImageBlobsContainer: {
		// borderWidth: 1,
		// borderColor: 'red',
		position: 'absolute',
		alignSelf: 'center',
		bottom: 0,
		width: '100%',
		// minWidth: responsiveWidth(20),
		// height: 50,
		flexDirection: 'row',
		justifyContent: 'center',
		alignItems: 'center',
		flexWrap: 'wrap'
	},
	primaryImageBlob: {
		color: '#fff59b',
		// color: '#104e01',
		marginHorizontal: 2,
		opacity: 0.85
	}
});
