export const clearedFilters = {
	"Breakfast": false,
	"Lunch": false,
	"Dinner": false,
	"Chicken": false,
	"Red meat": false,
	"Seafood": false,
	"Vegetarian": false,
	"Salad": false,
	"Vegan": false,
	"Soup": false,
	"Dessert": false,
	"Side": false,
	"Whole 30": false,
	"Paleo": false,
	"Freezer meal": false,
	"Keto": false,
	"Weeknight": false,
	"Weekend": false,
	"Gluten free": false,
	"Bread": false,
	"Dairy free": false,
	"White meat": false,
}
