import React from 'react'

export const filters = [
    "Breakfast",
    "Lunch",
    "Dinner",
    "Chicken",
    "Red meat",
    "Seafood",
    "Vegetarian",
    "Salad",
    "Vegan",
    "Soup",
    "Dessert",
    "Side",
    "Whole 30",
    "Paleo",
    "Freezer meal",
    "Keto",
    "Weeknight",
    "Weekend",
    "Gluten free",
    "Bread",
    "Dairy free",
]