import React from 'react'
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  mainPageContainer:{
    flex: 1,
  },
  background: {
    width: '100%',
    height: '100%',
    flex: 1
  },
  formRow: {
    flex: 1,
    marginTop: 4,
    flexDirection:'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 5,
    width: '100%',
    backgroundColor: 'white',
  },
  transparentFormRow: {
    flex: 1,
    marginTop: 4,
    flexDirection:'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    width: '100%',
  },
  createRecipeInputBox: {
     height: 44,
     justifyContent: 'center',
     width: '96%',
     marginLeft: '2%',
     marginRight: '2%',
   },
   createRecipeTextAreaBox: {
     marginLeft: '2%',
     marginRight: '2%',
     backgroundColor: 'white',
     height: 140,
     width: '96%',
   },
   newRecipeTextCentering: {
    // position: 'absolute',
   },
   createRecipeTextAreaInput: {
     height: 130,
     marginTop: 4,
   },
   timeAndDifficultyWrapper: {
    borderStyle: 'solid',
    borderWidth: 2,
    width: '100%',
    marginTop: 4,
    flex: 1,
    flexDirection:'row',
    justifyContent: 'center',
   },
   timeAndDifficultyTitleItem: {
       marginLeft: '5%',
       marginRight: '5%',
       backgroundColor: 'white',
       borderRadius: 5,
       height: 44,
       width: '35%',
       justifyContent: 'center',
       alignItems: 'center',
       borderStyle: 'solid',
       borderWidth: 1,
     },
   timeAndDifficultyTitle: {
    marginLeft: '5%',
    marginRight: '5%',
    fontSize: 16,
    color: "#505050",
    },
  timeAndDifficulty: {
        marginLeft: '5%',
        marginRight: '5%',
        backgroundColor: 'white',
        width: '35%',
        borderRadius: 5,
        borderStyle: 'solid',
        borderWidth: 1,
      },
  picker: {
    height: 44,
    borderStyle: 'solid',
    borderWidth: 1,
  },
  pickerText: {
    // textAlign: 'center'
  },
  createRecipeFormButton:{
    marginLeft: '5%',
    marginRight: '5%',
    justifyContent: 'center',
    alignItems: 'center',
    width: '35%',
    height: 44,
    flexDirection:'row',
    borderRadius: 5,
    backgroundColor: '#fff59b',
    borderStyle: 'solid',
    borderWidth: 1,
  },
  unitPicker: {
    margin: '5%',
    bottom: '2%',
  },
  createRecipeFormButtonText: {
    marginLeft: '5%',
    marginRight: '5%',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 14,
    color: '#104e01',
  },
  standardIcon: {
    color: '#104e01',
  },
  addIngredientQuantityInputBox: {
     marginRight: '2%',
     backgroundColor: 'white',
     height: 42,
     width: '37%',
     borderStyle: 'solid',
     justifyContent: 'center',
     borderWidth: 1,
     borderRadius: 5,
  },
  addIngredientUnitInputBox: {
     backgroundColor: 'white',
     justifyContent: 'center',
     height: 42,
     width: '61%',
     borderStyle: 'solid',
     borderWidth: 1,
     borderRadius: 5,
  },
  ingredientTextAdjustment: {
    marginLeft: 7,
  },
  autCompleteRowContainer: {
    flex: 1,
    marginTop: 4,
    flexDirection:'row',
    width: '100%',
  },
  autoCompleteContainer: {
    position: 'absolute',
    width: '51%',
     borderRadius: 5,
  },
  quantityAndUnitContainer: {
    marginLeft: '1%',
    width: '48%',
    left: '51%',
    flexDirection: 'row',
  },
  autoCompleteOuterContainerStyle: {
    borderRadius: 5,
  },
  autoCompleteInputContainerStyle: {
    borderRadius: 5,
    backgroundColor: 'white',
  },
  autoCompleteInput: {
    borderRadius: 5,
    backgroundColor: 'white',
    borderStyle: 'solid',
    borderWidth: 1,
    height: 42,
    paddingLeft: '4%',
  },
  autoCompleteList: {
    borderRadius: 5,
    height: 150,
    width: '90%',
    borderStyle: 'solid',
    borderWidth: 1,
  },
})
