export const emptyRecipe = {
	alertPopUpShowing: false,
	errors: [],
	newRecipeDetails: {
		recipeId: null,
		name: "",
		instructions: [],
		instructionImages: [],
		ingredients: [],
		difficulty: "0",
		times: {
			prepTime: 0,
			cookTime: 0,
			totalTime: 0,
		},
		primaryImages: [],
		filter_settings: {
			"Breakfast": false,
			"Lunch": false,
			"Dinner": false,
			"Chicken": false,
			"Red meat": false,
			"Seafood": false,
			"Vegetarian": false,
			"Salad": false,
			"Vegan": false,
			"Soup": false,
			"Dessert": false,
			"Side": false,
			"Whole 30": false,
			"Paleo": false,
			"Freezer meal": false,
			"Keto": false,
			"Weeknight": false,
			"Weekend": false,
			"Gluten free": false,
			"Bread": false,
			"Dairy free": false,
			"White meat": false,
		},
		cuisine: "Any",
		serves: "Any",
		acknowledgement: "",
		acknowledgementLink: "",
		description: "",
		showBlogPreview: false
	},
	instructionHeights: [], //responsiveHeight(6.5)],
	averageInstructionHeight: 0, //responsiveHeight(6.5),
}
